version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - fmorpionapi_network
  
  fmorpionapi:
    depends_on:
      - mysqldb
    container_name: fmorpionapi
    image: frymarshall/tassa_api
    command: ["./wait-for-db.sh"]
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $LOCAL_PORT:$DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - fmorpionapi_network

volumes: 
  db:
networks:
  fmorpionapi_network:
    driver: bridge